[package]
name = "leia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
easy-gltf = "0.1.5"
glam = "0.21"
rand = "0.8.5"
rayon = "1.5.3"
